language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script: pytest tests

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDIzZjM1MWRmLTY4ZTQtNDRjMC1iYzA5LTVhZjIyZjlkYzJkNwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYg-3_Mp3BSIxrtkbJZSvDNA5FRavMFbSRFsN6TZyqW1Vs"
  on:
    tags: true
    branch: master
